### ISSUE TITLE
Empty balance shows never ending progress indicator

### ISSUE THREAD

**Issue by biafra23** [CirclesUBI/circles-myxogastria#155]
### Expected behavior (I guess) 
A zero CRC balance should be shown as 0

### Observed behavior 
1. A progress indicator is shown instead
![image](https://user-images.githubusercontent.com/246473/104764396-a49e0700-5767-11eb-9687-1f21bcdb5897.png)
1. It seems that such an account also does not receive any UBI payments until the balance is above zero

### Steps to reproduce
1. Send all circles to another account

### Environment
URL: https://circles.garden
Platform: macOS
Browser: Firefox, Brave & Chrome

**Comment by louilinn** [comment]
This is almost impossible to reproduce with time circles conversion in garden. The balance can never become exactly 0 due to rounding and conversion imperfections. If the balance is loading it is because the account is still loading, not because it is 0.

This issue should have been closed earlier but is cleaned up now
