### ISSUE TITLE
Clarify image requirements for the avatar

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-myxogastria#202]
When you upload an image that doesn't have the right format an error shows up saying: `Could not upload image. Is it the correct format and size?`. However the user is not informed about the correct size and format.

**Comment by triaslucia** [comment]
Could you tell me the correct size and format? 
Then I will prepare the error text

**Comment by llunaCreixent** [comment]
The requirements for the profile picture are:   
 - jpeg, png
 - 5MB
 But we still find errors uploading some pictures that fulfill these requirements.
 It would be useful to collect examples of images that fail.

**Comment by triaslucia** [comment]
![20210713_185730](https://user-images.githubusercontent.com/38475134/127835781-3884acb2-a484-4de1-810d-0a90ce07269c.jpg)

**Comment by eminx** [comment]
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.circles.garden/api/uploads/avatar/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

This error indicates that the problem is not due to the nature of the image being tried to upload. 
It's about the security configurations in the server environment, making restrictions to allow serving only to safe clients.

So I think what we need to do is to whitelist our clients, like mentioned here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#examples

**Comment by llunaCreixent** [comment]
I would assume that if it wasn't due to the nature of the image, I would have the same error with a different image in the same test, right?

**Comment by llunaCreixent** [comment]
The size limit is actually 1MB, @triaslucia 
Now we just need to communicate it to the user :)

**Comment by triaslucia** [comment]
TEXT for the Error box: 

Ups, Something went wrong! 
Make sure your image is a jpeg or png of Max 1MB.
