### ISSUE TITLE
Indicate when profile is an organization

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-myxogastria#205]
We need some sort of indication if the currently viewed profile is an organization, like a little icon in a corner or something similar.

This should not only be visible on profile pages but also whenever a user profile pops up somewhere (for example when searching for users or when transferring Circles etc.).

This will also help to explain to the users when it is not possible to trust that particular account.

**Comment by triaslucia** [comment]
Here I'm posting the Figma file with the design for it.

*MAGENTA COLOR:* https://www.figma.com/file/xqLKVIJTMAKuwO2wYGbyeb/Shared-Wallets?node-id=4138%3A622

**Comment by eminx** [comment]
@adzialocha @triaslucia 

I couldn't see where the indicator sign for organisation in the figma file. Is it done?

I would suggest against using an icon, especially for this case. Because icons are always abstract and we only assume that people understand what they mean... But this is just a suggestion.

We could just have it written underneath the name with smaller font-size `organisation`..?

**Comment by triaslucia** [comment]
yes it is in there @eminx . With Magenta ( dark pink) color. With the title: Indicate when 
profile is an organization #205 . 

We are using a graphic to show the coming together of different tokens.
<img width="544" alt="Screenshot 2021-07-06 at 16 32 06" src="https://user-images.githubusercontent.com/38475134/124618262-ecc8f700-de77-11eb-83e0-95c8307c33e2.png">
