### ISSUE TITLE
Activate "enter" as a way to keep to next step

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#210]
**When I add my seed phrase I  can just keep to the next step if I manually click on the button "Next"**
After copying the seed phrase I automatically do enter, as an intuitive way of wanting to continue. But that adds an enter in my seedphrase and that generates problems. Because the seed phrase is then not read correctly. 

**to push "Enter" should function as to click on the "Continue" button**
I want that when I push enter, I will forward to the next screen.

**Comment by adzialocha** [comment]
Duplicate: https://github.com/CirclesUBI/circles-myxogastria/issues/136

**Comment by adzialocha** [comment]
Right now we're using a multiline input field so having support for "Enter" makes sense inside of it. Also, enter should not really break your seed phrase (of course if you don't change a word because of it) as all extra characters are filtered out when checking it.

I leave this open now as it is still part of #136 but would remove it from the Milestone if this is ok :+1:
