### ISSUE TITLE
Updating the  on-boarding

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#228]
We are updating the onboarding screens. 

1_Adding color backgrounds
2_Change first texts, adding a hyperlink to faq 

_Design material: in **Yellow color**_ https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/circles-myxogastria?node-id=3820%3A19832

**Comment by louilinn** [comment]
Hi @triaslucia Just wanted to double check a couple of things:
1) do we only want the turquoise background for the browser and no change for the mobile view? Is there an image for this? Is this in the figma file?
2) do we keep the progress dots at the top only for the mobile app or for both?

I am new to figma files and all ^^ thanks for the clear mockups!

**Comment by triaslucia** [comment]
It is all up-dated now @louilinn . Sorry, the filed looked like edited...
1. On Both
2. On Both
LINK: https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/circles-myxogastria?node-id=3921%3A2026

**Comment by mikozet** [comment]
Hi @triaslucia @louilinn,

I see that we change here as well how our slider works currently - instead of active state, dots react as a step progression... . Is it intentional? 
![Zrzut ekranu 2021-12-9 o 11 40 26](https://user-images.githubusercontent.com/95082155/145383110-3ca31c7e-1d13-48e7-bcf0-c41c0ad9488a.png)

(I broke second screen elipse - sorry for that ;) )

**Comment by mikozet** [comment]
@triaslucia I will also change background of Header from transparent to white as it is fixed to top during scrolling process
