### ISSUE TITLE
Edit profile  picture and name

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#237]
**The Profile information such as name and picture does not allow modification**
We want to mek the Picture and name profile editable. 

**Create a edit profile screen **
I want people to be able to edit their name and picture profile within a few clicks.
Also in the case of Shared Wallets

Enable to take a picture with the camara should be in 'Edit profile' and 'Onboarding'
_Design Material_ ORANGE: https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/circles-myxogastria?node-id=3820%3A19832

**Comment by louilinn** [comment]
From meeting discussion:
Concern that other users become confused if the names are changed. 
Maybe we can add a text explaining that this is a dangerous change for the user. And that anyone can 

It could be good to divide the task to do one edit update at a time in terms of work

The transaction history of the user interaction is still there to identify the user for other users.

**Comment by louilinn** [comment]
@triaslucia 
Since we are replacing the link our own "profile" view to an "edit profile" view I was wondering:
Do we want to replace the share button that exists on the profile view atm (classic 3 connected dots symbol) 
Similar functionality exist when going to the "Show QR-code" view and there is a "Share" button. Maybe the path to this code be clearer or have clearer buttons. Just a though :) for another issue. 

The QR-code view "Share" generates this: 
Hey! Check out my Circles UBI profile! http://localhost:8080/profile/0x800C979850f64CD1A023feB9e67FbacA312eD398
The share symbol generaltes this: 
Check out my Circles UBI profile! http://localhost:8080/profile/0x800C979850f64CD1A023feB9e67FbacA312eD398

Also maybe share button should say copy sharing message to clipboard or something?

**Comment by louilinn** [comment]
API issue: https://github.com/CirclesUBI/circles-api/issues/91
Core issue: https://github.com/CirclesUBI/circles-core/issues/123

**Comment by mikozet** [comment]
What's left:
- [x] prepare UI
- [x] add backend for upload functionality
- [x] add backend for get email data
- [x] update frontend with new API call to update profile data and also get email data

**Comment by mikozet** [comment]
We found out that the email is private (unlike the username and avatar), so the backend to modify the email requires a little bit of more work. Because of that we resigned from adding possibility to edit email for the moment

**Comment by mikozet** [comment]
Hi @triaslucia , 
Edit profile is updated with changes proposed on design https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4349%3A8713 
(not on preview yet - that PR: https://github.com/CirclesUBI/circles-myxogastria/pull/484 needs to be merged): 

Few questions although:
![Zrzut ekranu 2022-09-23 o 12 23 48](https://user-images.githubusercontent.com/95082155/191941280-935bbce8-22a5-42a2-8337-7fba64aaa51d.png)
I see some buttons change design (Edit Profile, Share Profile)..
Is that a change which should be implemented only on that view or is it more component change so (Trust people, Send Circles) buttons should also be affected?

 ![Zrzut ekranu 2022-09-23 o 12 23 54](https://user-images.githubusercontent.com/95082155/191941555-725d463f-5b27-45ed-a082-16dd7a7f6d3c.png)
Is that a hover state?

**Comment by triaslucia** [comment]
1_ Its a components change. Meaning you are right, "Trust People - Send Circles" should also be affected. 

2_Yes it is a Hover state ( you can see in the info of the component on the side bar of  Figma.

**Comment by mikozet** [comment]
@triaslucia that button change is a part of refactoring buttons it will come with this task:
https://github.com/CirclesUBI/circles-myxogastria/issues/436

**Comment by louilinn** [comment]
Closed by #449
