### ISSUE TITLE
Bug in Notifications when my Org trusts another wallet

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/circles-myxogastria#269]
If an organization that I own trusts another wallet, in my individual wallet's notification view says that "I trust my organization". I expect that I don't see that notification in my individual wallet (also the message is incorrect).

**Comment by louilinn** [comment]
If you could include more information like a screenshot of the notification and what notification you would expect because I guess some notification makes sense?

**Comment by llunaCreixent** [comment]
Yes! The thing is that they dissapeared. mmmm... it seems the app gets confused when you change accounts

**Comment by mikozet** [comment]
I think I understand the issue and replication steps for me are:
1. Create individual account
2. Create organisation account using the one from point 1
3. Trust from organisation account some other person
4. You will get notification on the individual account with wrong message, instead of notification from organisation account..
Is that correct @llunaCreixent ?

**Comment by triaslucia** [comment]
Did we implemented some change on this already? 

From UX perspective, it makes sense that notifications get split according to the wallet they belong to. 

So the flow should look like: 

1_Create individual account
2_Create Shared Wallet using the one from point 1
3_Trust from  Shared Wallet a person
4_Get a push-up notification while being at the SW  on either cases "successfully trusted" or "something went wrong"

5_ If I switch to my Individual Wallet. In there I only receive notification regarding the actions of my Individual Wallet.

**Comment by louilinn** [comment]
No longer reproducable
