### ISSUE TITLE
Correct Backgounds on deskptop version 

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#326]
So far the Background starts on Mobile as circle and turns into an Oval on desktop version. 

◦ It should increase on size maintaining the proportional shape. 
◦ Change color in case of Shared Wallets. 

**See under "SCREEN BACKGROUND":**  https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4673%3A9745

_the shape looks like this_ 
<img width="1673" alt="Screenshot 2022-04-05 at 14 50 52" src="https://user-images.githubusercontent.com/38475134/161943270-6c02530d-6e45-4964-a73c-8907bb259e25.png">
<img width="1679" alt="Screenshot 2022-04-05 at 15 21 40" src="https://user-images.githubusercontent.com/38475134/161943288-142e7157-a02c-4e08-a0a4-5a0530e3667e.png">

_the shape should Look Like This_ 

<img width="515" alt="Screenshot 2022-04-06 at 11 27 55" src="https://user-images.githubusercontent.com/38475134/161943740-112a6614-13c3-4f2d-a87f-0be2b9497726.png">

**Comment by mikozet** [comment]
Hi @triaslucia 
So background turns oval in desktop version as here https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=435  it was like that:
![Zrzut ekranu 2022-04-26 o 15 33 55](https://user-images.githubusercontent.com/95082155/165312001-9c482234-3786-483d-b0a6-cd7c427a21d4.png)
0%3A18052

If we increase a size maintaining proportional shape we end up getting this on desktop:
![Zrzut ekranu 2022-04-26 o 15 37 02](https://user-images.githubusercontent.com/95082155/165312461-19bf2e4f-7510-4732-968a-5db6e4c1e5a4.png)
or another possible solution:
![Zrzut ekranu 2022-04-26 o 15 36 38](https://user-images.githubusercontent.com/95082155/165312517-1afd5e55-f9ad-4ac9-aeb6-311485d621d4.png)

because of that we decided ouie to make that similar how it is in Onboarding tutorial just inverted - image below 
![Zrzut ekranu 2022-04-26 o 21 36 39](https://user-images.githubusercontent.com/95082155/165378676-54da2f36-1b98-48b4-bc0a-bad13691d32d.png)

Let me know if that makes sense or should we adjust it or do it differently

**Comment by mikozet** [comment]
Here is a link to our discussion with ouie: https://github.com/CirclesUBI/circles-myxogastria/pull/278

**Comment by louilinn** [comment]
Duplicate https://github.com/CirclesUBI/circles-myxogastria/issues/347
