### ISSUE TITLE
Remove dependency on MaxFlow calculation when sending transfers

### ISSUE THREAD

**Issue by houndbee** [CirclesUBI/circles-myxogastria#457]
**Is your feature request related to a problem? Please describe.**

Currently, when trying to send a CRC transfer, the user has to wait until the maximum amount has been calculated before the text field to input the value of the CRC transaction is enabled. The text field is not enabled if the maximum amount cannot be calculated successfully(timeout, path too complex, etc.), and the maximum amount shows as 0.

**Describe the solution you'd like**

I suggest removing the dependency and allowing the user send a transaction even if the max amount cannot be calculated successfully.  Also, if the Max amount calculation fails, display a descriptive message such as "Maximum amount cannot be calculated at this time." instead of a "0".

**Comment by mikozet** [comment]
It looks like we do not have mechanism `Max amount calculation fails` so I removed dependency of max amount and if it calculates as 0 there is a message `Maximum amount cannot be calculated at this time.`

**Comment by mikozet** [comment]
"Also, if the Max amount calculation fails, display a descriptive message such as "Maximum amount cannot be calculated at this time." instead of a "0"."
This should work now correctly

**Comment by mikozet** [comment]
![Zrzut ekranu 2022-08-29 o 15 04 08](https://user-images.githubusercontent.com/95082155/187213029-fd45ac4b-0793-42c5-8b93-d6b803117577.png)
![Zrzut ekranu 2022-08-29 o 15 04 02](https://user-images.githubusercontent.com/95082155/187213038-86c2248a-9bb4-47ce-9a46-5b6ec390859d.png)
These are current problems. It looks like it is not frontend issue. 
I revert back to f20e6fe5ee5eed7591b573d763683f75302ee797 (as it was a plaace where it was working) 
I verified and problems from attached scrennshots appeared.
I updated f20e6fe5ee5eed7591b573d763683f75302ee797 with main changes and verified again with the same result

In order to test try to send 1 CRC from CirclesCoop wallet (you need to get access) to MADAMEZORRO.
This transfer was passing before
