### ISSUE TITLE
Basic CSV export for transactions MVP

### ISSUE THREAD

**Issue by houndbee** [CirclesUBI/circles-myxogastria#460]
**Story: User clicks a button "Export Balance" in transaction tab in Activity Log. A csv file is downloaded containing an account statement for the latest transactions**

Add a "Export to CSV" button in the transaction activity log to let a user download all transactions to/from their wallet. 

Default behaviour: Export the last transactions.
**No visual implementation** in this task, just the simplest button to download csv for a default interval.

**Comment by louilinn** [comment]
A speification will be added soon, reind me if needed

**Comment by louilinn** [comment]
#### CVS format
What a csv file should look like:
```
"Circles Account Statement"
account_name, Aaaaa
account_safe_address, 0x00000000000000000000
period_start_date", dd.mm.yyyy
period_end_date, dd.mm.yyyy
balance_on_end_date, xxxxx.xx
demurrage_during_selected_period, -xxx.xx
date, to_or_from_username, to_or_from_safe_address, tranfer_note, amount_in_circles
dd.mm.yyyy, Aaaaa, 0x00000000000000000000, "Aaa aa aaaaaa aaaa", xxx.xx
dd.mm.yyyy, Aaaaa, 0x00000000000000000000, "Aaa aa aaaaaa aaaa", xxx.xx
dd.mm.yyyy, Aaaaa, 0x00000000000000000000, "Aaa aa aaaaaa aaaa", xxx.xx
dd.mm.yyyy, Aaaaa, 0x00000000000000000000, "Aaa aa aaaaaa aaaa", xxx.xx
dd.mm.yyyy, Aaaaa, 0x00000000000000000000, "Aaa aa aaaaaa aaaa", xxx.xx
dd.mm.yyyy, Aaaaa, 0x00000000000000000000, "Aaa aa aaaaaa aaaa", xxx.xx
balance_on_start_date xxxxx.xx
```

#### More info:
Username or safe address? Both

TC or CRC?:
TC. We should have it in the way of what we currently see in the wallet. 
The value of transactions are the TC value at the time of the transaction. 
In the export we include the demurrage in TC over the period, should be displayed. This is calculated as the difference between start_balanc+/- all_transactions and end_balance. As there will be a difference between the balance. So an accountant can have it clear for taxation, and the numbers add up correctly. 

Number of decimals: 2 decimals for all amounts

Date - format of datestamp: As in figma: dd.mm.yyyy

**Comment by louilinn** [comment]
Suggestion:
start by exploring the response by calling getLatest similar to
https://github.com/CirclesUBI/circles-myxogastria/blob/0c4a33546636dbf2c19f376844167e720682eed4/src/store/activity/actions.js#L127
but with:
timestamp jan 1st 2023
limit - high number
offset?
filter TRANSFER

**Comment by louilinn** [comment]
- [x] get a response from core/graph of all transactions after a certain date (using getLatest with TRANSFER filter)
- [ ] ignore transactions after the end date
- [x] format the remaining transactions into the csv-formatted strings for each transactions (dd.mm.yyyy, Aaaaa, 0x00000000000000000000, "Aaa aa aaaaaa aaaa", xxx.xx)
- [x] get start balance
- [x] get end balance
- [x] calculate the demmurage
- [x] put everything into the same csv file

**Comment by louilinn** [comment]
### Balances
Getting the balance for a certain timestamp is probably not possible through the graph
https://github.com/CirclesUBI/circles-core/blob/cdb17577e9cc4bcdbfb5b9b17fd3242b501d63bb/src/utils.js#L300

Option: 
1. get Balance (in CRC) for today (ok)
2. get the transactions since start date from activity (in CRC)
3. subtract transactions backwards to calculate the balance in CRC for a certain date
4. convert to TC

**Create one method returning the csv data that**
- call getLatest (activities) [start-now]
- call getBalance (now, CRC)
- one filter of transaction from end date [end-now]
- call calcultateBalanceInTC at date (x2 for start and end dates) 
    - params: transaction activities from one date (in CRC), date
    - subtract the transactions in CRC
    - call TC conversion on the result
- filter out late transactions [start-end] 
- call TC conversion on remaining transfers in loop *1
- calculate demurrage
    - params: transactions in TC, balances in TC
    - sum up the TC transactions (based on *1)
    - calculate difference
- call txToCsv for each transaction *2
- generate CSV string and file

*don't use formatCircles but do the same things in different steps
call the npm package at *1 and round txToCsv (*2)
reference:
https://github.com/CirclesUBI/circles-myxogastria/blob/0f7652ac9c3f9e07bfb7bb5c0a09f68f1099c33c/src/utils/format.js#L23

**Unit tests**
- demmurrage calc
- get balance at date
- filtering transactions based on
- csv transaction generation
- csv file generation
