### ISSUE TITLE
Maximum amount of transfer is 0

### ISSUE THREAD

**Issue by triaslucia** [CirclesUBI/circles-myxogastria#489]
**Describe the bug**
Maximum amount of transfer is 0 or cannot be calculated.

**Additional context**
This are the account facing this issue: 

sender: @Colorinteam reciever:@ZeroWasteBerlin

sender: @erazerowaste Reciever:@teeboy99

sender:@HerbieUnverpackt Reciever:@CirclesCoop

**Comment by JacqueGM** [comment]
This happens because, depending on the amount between two accounts the API takes more or less time. For larger amount it takes a lot of time, and within the API there is a limit on how long to wait until the results is given. If the times to return this response is larger than than this value then this error appears on myxo. By increasing the times in both nginx and the api this issue can be closed. But there is still the issue with larger amount and also reduce the time the pathfinder takes to find steps. Here the new issue description https://github.com/CirclesUBI/circles-transfer/issues/13

**Comment by louilinn** [comment]
Iterative queries will be added to the new service pathfinder service that will be worked on this spring.

The pathfinder2 that will be integrated in the app this month has an input of a number of hops (how far away in the network to look). Limiting this can potentially solve this. We would not like to try something else regarding this issue before the new pathfinder is integrated.

Another option is to try asking for lower maximums if the max-max takes too long to calculate.
