### ISSUE TITLE
Correct Pink Shadow so it does not contain empty space

### ISSUE THREAD

**Issue by mikozet** [CirclesUBI/circles-myxogastria#531]
Subtask of https://github.com/CirclesUBI/circles-myxogastria/issues/396

Hi @ruchajoshi08 
Our current pink shadow is too high and because of that some content might not be clickable.
Could we redesign it in a way that it's height doesn't affect content not being clicked 
Current pink shadow has around 300px height but it could have around 80px or 100px as rest of it looks transparent.
That transparent part causes that we cannot click content below of it..

![Zrzut ekranu 2022-11-4 o 11 25 51](https://user-images.githubusercontent.com/95082155/199952434-597c146a-5577-4d1c-81d4-3dcf9cd6870e.png)
![Zrzut ekranu 2022-11-4 o 11 26 00](https://user-images.githubusercontent.com/95082155/199952439-9309c06a-66c7-4647-89f3-9b8b72170035.png)
![Zrzut ekranu 2022-11-4 o 11 26 06](https://user-images.githubusercontent.com/95082155/199952440-ea60bcce-9aa9-4d0d-bbe2-3232eeda7636.png)

**Comment by ruchajoshi08** [comment]
@mikozet I changed the height to 80px for mobile and 150 for desktop. will it work better now?

**Comment by mikozet** [comment]
> 

@ruchajoshi08 probably yes - could you share a link to design?

**Comment by ruchajoshi08** [comment]
https://www.figma.com/file/ZTqF54s6CSHTwAxp0U0JjQ/Circles-myxogastria?node-id=4350%3A26250 here is the link

**Comment by triaslucia** [comment]
We still need to fix the shadow. 

-It is too rectangular. We should increase the blurring so that it gets gradually lost, for this it is necessary to increase the height of the surface that covers the shade. 
![Screenshot 2023-02-16 at 09 57 36](https://user-images.githubusercontent.com/38475134/219317153-d300c050-7d9c-464f-a99d-733d7dd88ffb.png)


- There are other issues related to this. So we should treat it a separate thing. 
- It will never be like the design. Should be in HTML, and this makes some changes. 
- We could try to use PNG instead of SVG.
- we are using CSS, but it is not so easy to imitate 100%
- The shadow is now covering other components, and this creates problems This components get inactive as the are under the shadow. 
-

**Comment by mikozet** [comment]
Closing as it is solve here:
https://github.com/CirclesUBI/circles-myxogastria/pull/615
