### ISSUE TITLE
When shared wallet is successfully created the app should return to its new dashboard

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-myxogastria#614]
**Describe the bug**
During shared wallet creation: app does not automatically return to dashboard when account is successfully created.
Instead the loading wheel persists until refresh.

**To Reproduce**
1. Create a shared wallet
2. Wait
3. After 5 minutes, see that the loading persists
4. Refresh the page and discover that the wallet was actually done setting up

**Expected behavior**
When shared wallet is successfully created the app should return to its new dashboard

---
This error is reproduceable in local development using dockers and is expected to be purely UI related.

branch code off main

**Comment by JacqueGM** [comment]
after trying again in Production, I can see the following: after 5 min the account is created and the backend logs it can be seen that right after the transaction is executed correctly an estimation is triggered again, which could be leading to this behaivour

**Comment by mikozet** [comment]
After wallet creation we enter a prefund phase which is the source of the problem. 
From frontend perspective the process works fine as we try to retry if prefund phase fails and after 3 retries we throw an error (it can be observed after 30-45min) and redirect user to /organization view where he can retry account creation.
The reason why user sees loading screen is that retry process which takes a bit long time.. 

It looks like prefund phase is not working correctly due wrong estimate.
That's why a hot fix has been added here: 
https://github.com/CirclesUBI/safe-relay-service/pull/71/commits/544cf0518f155966407114ef06ecb6a01c68ae7c

**Comment by louilinn** [comment]
I understand this as resolved @mikozet ?
It returned to dashboard correctly when I did support with user on Wednesday? 
I am closing. Reopen if not resolved please
